# Generated by Django 5.2.1 on 2025-07-16 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('expiry_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DispensedMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_id', models.IntegerField()),
                ('quantity_dispensed', models.FloatField()),
                ('dispensed_date', models.DateTimeField()),
                ('pharmacy_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.pharmacyitem')),
            ],
        ),
    ]
