# Generated by Django 5.1.7 on 2025-07-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensedmedicine',
            name='dispensed_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='dispensedmedicine',
            name='prescription_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dispensedmedicine',
            name='quantity_dispensed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pharmacyitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
