# Generated by Django 5.2.1 on 2025-07-22 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_alter_dispensedmedicine_dispensed_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacyitem',
            name='expiry_date',
        ),
        migrations.AddField(
            model_name='pharmacyitem',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispensedmedicine',
            name='prescription_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dispensedmedicine',
            name='quantity_dispensed',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pharmacyitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
