# Generated by Django 5.1.6 on 2025-07-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('receptionist', 'Receptionist'), ('doctor', 'Doctor'), ('labtech', 'Lab Technician'), ('pharmacist', 'Pharmacist'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
    ]
