# Generated by Django 5.1.7 on 2025-07-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=6),
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
