# Generated by Django 5.1.7 on 2025-07-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_appointment_doctor_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
