# Generated by Django 5.2.1 on 2025-07-20 14:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_test', '0001_initial'),
        ('patients', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='price',
        ),
        migrations.AddField(
            model_name='labtest',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='labtest',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='labtest',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='test_name',
            field=models.CharField(choices=[('Blood Test', 'Blood Test'), ('X-Ray', 'X-Ray'), ('MRI', 'MRI')], max_length=50, null=True),
        ),
    ]
