# Generated by Django 5.1.7 on 2025-07-21 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_test', '0002_remove_labtest_price_labtest_cost_labtest_date_and_more'),
        ('patients', '0004_remove_patient_status_patient_allergies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
    ]
